##FROM ubuntu:latest
##LABEL authors="Eridas"
##
##ENTRYPOINT ["top", "-b"]
#
## Use the official Python image from the DockerHub
#FROM python:3.8-slim
#
## Set the working directory
#WORKDIR /app
#
## Copy the requirements.txt file to the container
#COPY requirements.txt .
#
## Install the dependencies
#RUN pip install --no-cache-dir -r requirements.txt
#
## Copy the rest of the application code to the container
#COPY . .
#
## Expose the port the app runs on
#EXPOSE 5000
#
## Command to run the application
#CMD ["python", "run.py"]
